config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  get 'donate/index'

  get 'subscriptions/index'

  get 'subscriptions/plans'

  get 'subscriptions/stripe_checkout'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  match 'users/show/:id', to: 'users#show', via: 'get', as: 'users_show'
  match '/stripe_checkout' => 'subscriptions#stripe_checkout' , via: 'post'
  match '/pay_with_paypal' => 'subscriptions#pay_with_paypal' , via: 'post'
  resources :feeds do
    resources :comments
  end
  resources :feeds do
    member do
      put "like" => "feeds#upvote"
      put "unlike" => "feeds#downvote"
      put "unvote" => "feeds#unvote"
    end
  end

  resources :conversations do
    resources :messages, only: [:create]
  end

  resources :notifications

  post 'pusher/auth'
  root 'feeds#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    can :access, :rails_admin   # grant access to rails_admin
    can :dashboard              # grant access to the dashboard
    can :create , Feed
    can :update , Feed do |feed|
        feed.user.try(:username) == user.username
    end
    can :destroy, Feed do |feed|
        feed.user.try(:username) == user.username
    end
    can :destroy, Comment do |c|
        c.user.try(:username) == user.username
    end
    can :upvote, Feed
    can :downvote, Feed
    can :unvote, Feed
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :feed
  belongs_to :user
  validates :body, presence: true,length: { within: 1..200 }
  
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  end

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/models/feed.rb
class Feed < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	
  validates :text, presence: true,length: { within: 1..200 }
  belongs_to :user
  acts_as_votable

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :feed
  belongs_to :comment
  belongs_to :conversation


  def set_read
    self.read = true
  end

  def self.set_conversation_notification(recipient_id, sender_id, conversation)
    new_notification = Notification.create(read: false , user_id: recipient_id, sender_id: sender_id,conversation_id: conversation)
    new_notification.save
  end

  def self.get_count(user_id)
    User.find(user_id).notifications.where(read: false).count
  end

  def sender
    User.find(self.sender_id)
  end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validates :first_name, presence: true,
                    length: { minimum: 2 }
  validates :username, presence: true,
                    length: { minimum: 2 }, uniqueness: { case_sensitive: false }
  # validates :avatar, presence: true
  validates :time_zone, presence: true

  has_many :feeds, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  acts_as_voter

  def clear_conversation_notifications(conversation_id)
    self.notifications.where(conversation_id: conversation_id).each do |n|
      n.update_attributes(read: true)
    end
  end

end

app/controllers/donate_controller.rb
class DonateController < ApplicationController
  def index
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
	# http_basic_authenticate_with name: "root", password: "passpass", except: [:index, :show]
	# before_action :authenticate_user! , except: [:index, :show]
	load_and_authorize_resource except: [:create, :index]

	def new
		@feed = current_user.feeds.build
	end

	def index
		@feeds = Feed.all
		@feed = Feed.new
		respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
		end
	end

	def create
		@feed = current_user.feeds.build(feed_params)
		@feed.name = current_user.username
		respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.js
      else
        format.html { render action: "index" }
        format.js
      end
    end
	end

	def edit
		@feed = Feed.find(params[:id])
	end

	def update
		@feed = Feed.find(params[:id])
		respond_to do |format|
			if @feed.update(feed_params)
	      format.html { redirect_to feeds_path }
	      format.js
			else
				format.html { render :edit }
	      format.js
			end
		end
	end

	def show
		@feed = Feed.find(params[:id])
	end

	def destroy
		@feed = Feed.find(params[:id])
		@feed.destroy
		respond_to do |format|
      format.html { redirect_to feeds_url,notice: 'Feed was successfully deleted.' }
      format.js
    end
	end

	def upvote
		@feed = Feed.find(params[:id])
		@feed.upvote_by current_user
		respond_to do |format|
			if @feed.upvote_by current_user
				format.html { redirect_to :back }
				format.js
			end
		end
	end

	def unvote
		@feed = Feed.find(params[:id])
		@feed.unvote_by current_user
		respond_to do |format|
			if @feed.unvote_by current_user
				format.html { redirect_to :back }
				format.js
			end
		end
	end

	def downvote
		@feed = Feed.find(params[:id])
		@feed.downvote_by current_user
		respond_to do |format|
			if @feed.downvote_by current_user
				format.html { redirect_to :back }
				format.js
			end
		end
	end

	
	private
	def feed_params
		params.require(:feed).permit(:name,:text)
	end

end

app/controllers/pusher_controller.rb
class PusherController < ApplicationController
  protect_from_forgery :except => :auth # stop rails CSRF protection for this action

  def auth
    if current_user
      response = Pusher[params[:channel_name]].authenticate(params[:socket_id])
      render :json => response
    else
      render :text => "Not authorized", :status => '403'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def pusher_include_tag(version)
    domain = if request.ssl?
               'https://d3dy5gmtp8yhk7.cloudfront.net'
             else
               'http://js.pusher.com'
             end

    javascript_include_tag "#{domain}/#{version}/pusher.min.js"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
	
end

app/helpers/messages_helper.rb
module MessagesHelper
  def self_or_other(message)
    message.user == current_user ? "self" : "other"
  end

  def message_interlocutor(message)
    message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipient
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def conversation_interlocutor(conversation)
    conversation.recipient == current_user ? conversation.sender : conversation.recipient
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/feeds/_feed.html.erb
<div class="col-md-6 blog-main box">
    <div class="bs-component">
    <div class="alert alert-dismissible boxbackgroundcolor" id="feed<%= feed.id%>">
      <button class="close" data-dismiss="alert" type="button">×</button>
      <% if feed.user.avatar.url %>
        <strong><%= link_to image_tag(feed.user.avatar.url, :class=> "img-circle", size: "40"), users_show_path(feed.user_id) , title: feed.user.username %> </strong>
      <% else %>
          <strong><%= link_to feed.user.username , users_show_path(feed.user_id) %> </strong>
      <% end %>
      <%= link_to feed.text, feed %>
      <time datetime="<%= feed.updated_at %>" title="<%= feed.updated_at.strftime("%d %b  %Y at %I:%M%p") %>">
        <h6><%= time_ago_in_words(feed.updated_at)+" ago."%> </h6>
      </time>
      <hr class="margin5">
      <%= render partial: "votes", locals: {feed: feed} %>
      <span class="pull-right" >
      <% if user_signed_in? %>
          <% if can? :update, feed %>
                <button type="button" class="btn btn-xs" data-toggle="modal" data-target="#myupdatefeed_<%=feed.id%>"><i class="fa fa-pencil-square-o">Edit</i></button>
          <% end %>
          <% if can? :destroy, feed %>
                <%= link_to feed, method: :delete, remote: true, data: {confirm: "Are you sure?"} do %>
                    <i class="fa fa-lg fa-trash-o"></i>
                <% end %>
          <% end %>
      <% end %>
      </span>
      <%= render partial: "comments/quickcomment", locals: {feed: feed} %>
    </div>
  </div>
</div>

<%= form_for(feed, :method => :put, remote: true) do |f| %>
    <div class="modal fade" id="myupdatefeed_<%= feed.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Edit</h4>
          </div>
          <div class="modal-body">

            <div class="field">
              <%= f.label :Feed %>
              <%= f.text_area :text, class: "form-control"%>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" id="mynewpostclose">Close</button>
            <%= submit_tag "Update", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/feeds/_form.html.erb
<%= form_for @feed, remote: true, :html => {:required => true} do |f| %>
 
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@feed.errors.count, "error") %> prohibited
        this feed from being saved:
      </h2>
      <ul>
        <% @feed.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.text_area :text,:class=> "form-control feed_content",:placeholder=> "Keep within 1 to 200 letters !", :required => "required",:maxlength=>"200" %>
  </p>
  <p>
    <%= f.submit " Feed It !", class: "btn btn-primary btn-sm pull-right"%>
  </p>
<% end %>

app/views/feeds/_votes.html.erb
<%= link_to pluralize(feed.comments.count, 'comment'), feed, class: "btn btn-xs"  %>
<% if user_signed_in? %>
    <% if current_user.voted_up_for? feed  %>
        <%= link_to unvote_feed_path(feed), method: :put,remote: true, class: "btn btn-xs" do %>
            <%= feed.get_upvotes.size %>
            <i class="fa fa-thumbs-up fa-lg"></i>
        <% end %>
    <% else %>
        <%= link_to like_feed_path(feed), method: :put,remote: true, class: "btn btn-xs" do %>
            <%= feed.get_upvotes.size %>
            <i class="fa fa-thumbs-o-up fa-lg"></i>
        <% end %>
    <% end %>
    <% if current_user.voted_down_for? feed  %>
        <%= link_to unvote_feed_path(feed), method: :put,remote: true, class: "btn btn-xs" do %>
            <%= feed.get_downvotes.size %>
            <i class="fa fa-thumbs-down fa-lg"></i>
        <% end %>
    <% else %>
        <%= link_to unlike_feed_path(feed), method: :put,remote: true, class: "btn btn-xs" do %>
            <%= feed.get_downvotes.size %>
            <i class="fa fa-thumbs-o-down fa-lg"></i>
        <% end %>
    <% end %>
<% else %>
    <%= link_to like_feed_path(feed), method: :put,remote: true, class: "btn btn-xs" do %>
        <%= feed.get_upvotes.size %>
        <i class="fa fa-thumbs-o-up fa-lg"></i>
    <% end %>
    <%= link_to unlike_feed_path(feed), method: :put,remote: true, class: "btn btn-xs" do %>
        <%= feed.get_downvotes.size %>
        <i class="fa fa-thumbs-o-down fa-lg"></i>
    <% end %>
<% end %>

app/views/feeds/create.js.erb
$(".feed_content").val('');
$("#container_feeds").prepend('<%= j render @feed  %>');

app/views/feeds/destroy.js.erb
$("#feed<%= @feed.id%>").remove();

app/views/feeds/downvote.js.erb
$("#feed<%= @feed.id%>").remove();
$("#container_feeds").prepend('<%= j render @feed  %>');

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form'%>
 
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-body">
          <% if user_signed_in? %>
              <%= render 'form'%>
          <% else %>
              <p>Sign In Please ! </p>
              <%= render 'devise/sessions/form' %>
          <% end %>
        </div>
      </div>
    </div>
</div>

<div class="row" id="container_feeds">
    <%= render @feeds.reverse %>
</div>

app/views/feeds/new.html.erb
<h1>Post New Feed</h1>
<%=  render 'form' %>
<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<div class="col-md-6">
    <div>
      <%= link_to :back do  %>
          <i class="fa fa-long-arrow-left fa-2x"></i>
      <% end %>
    </div>
  <br>
  <div class="bs-component">
    <div class="alert alert-dismissible boxbackgroundcolor">
    <p>
      <%= image_tag(@feed.user.avatar.url, :class=> "img-circle", size: "60") %>
    </p>
    <p>
      <%= link_to @feed.user.username, users_show_path(@feed.user_id) %>
    </p>


    <p>
      <i class="fa fa-quote-left fa-fw"></i>
      <%= @feed.text %>
      <i class="fa fa-quote-right fa-fw"></i>
    </p>

    <h5>
      Created
      <%= time_ago_in_words(@feed.created_at)+" ago" %>
    </h5>

    <h6>
      Last Updated
      <%= time_ago_in_words(@feed.updated_at)+" ago" %>
    </h6>


      <hr class="margin5">

    <% if user_signed_in? %>
        <% if current_user.voted_up_for? @feed %>
            <%= link_to unvote_feed_path(@feed ), method: :put, class: "btn btn-success btn-xs" do %>
                <%= @feed.get_upvotes.size %>
                <i class="fa fa-thumbs-up fa-lg"></i>
            <% end %>
        <% else %>
            <%= link_to like_feed_path(@feed ), method: :put, class: "btn btn-success btn-xs" do %>
                <%= @feed.get_upvotes.size %>
                <i class="fa fa-thumbs-o-up fa-lg"></i>
            <% end %>
        <% end %>
        <% if current_user.voted_down_for? @feed   %>
            <%= link_to unvote_feed_path(@feed ), method: :put, class: "btn btn-warning btn-xs" do %>
                <%= @feed.get_downvotes.size %>
                <i class="fa fa-thumbs-down fa-lg"></i>
            <% end %>
        <% else %>
            <%= link_to unlike_feed_path(@feed ), method: :put, class: "btn btn-warning btn-xs" do %>
                <%= @feed.get_downvotes.size %>
                <i class="fa fa-thumbs-o-down fa-lg"></i>
            <% end %>
        <% end %>
    <% else %>
        <%= link_to like_feed_path(@feed), method: :put, class: "btn btn-success btn-xs" do %>
            <%= @feed.get_upvotes.size %>
            <i class="fa fa-thumbs-o-up fa-lg"></i>
        <% end %>
        <%= link_to unlike_feed_path(@feed), method: :put, class: "btn btn-warning btn-xs" do %>
            <%= @feed.get_downvotes.size %>
            <i class="fa fa-thumbs-o-down fa-lg"></i>
        <% end %>
    <% end %>
      <span class="pull-right">
          <% if user_signed_in? %>
              <% if can? :update, @feed %>
                  <button type="button" class="btn btn-xs" data-toggle="modal" data-target="#myupdatefeed_<%= @feed.id%>"><i class="fa fa-pencil-square-o">Edit</i></button>
                  <% end %>
                  <% if can? :destroy, @feed %>
                      <%= link_to @feed, method: :delete, data: {confirm: "Are you sure?"} do %>
                      <i class="fa fa-lg fa-trash-o"></i>
                  <% end %>
              <% end %>
          <% end %>
      </span>

    <% if @feed.get_downvotes.voters.any? %>
        <h6>Unliked By: <% @feed.get_downvotes.voters.reverse.each do |p| %><%= link_to(p.username, users_show_path(p.id)) %> <% end %></h6>
    <% end %>

    <% if @feed.get_upvotes.voters.any? %>
        <h6>Liked By: <% @feed.get_upvotes.voters.reverse.each do |p| %><%= link_to(p.username, users_show_path(p.id) ) %> <% end %></h6>
    <% end%>

    </div>
  </div>
    <p>Comments:</p>
    <div id="comment_container">
        <% if @feed.comments.any? %>
                <%= render @feed.comments.reverse %>
        <% else %>
            <p id="no-comment">No Comments on this Feed, Be the first one !</p>
        <% end %>
    </div>


</div>
<div class="col-md-6">
  <br>
  <br>
  <div class="fixed-element-right">
      <div class="bs-component">
        <div class="alert alert-dismissible boxbackgroundcolor">
        <% if user_signed_in? %>
            <%= render 'comments/form' %>
        <% else %>
            <p>To Post Comment, Please Sign In !
            <%= render 'devise/sessions/form' %>
            <%= link_to "Forgot your password?", new_password_path(resource_name) %>
            </p>
              <p>
                <%= link_to "Sign Up", new_user_registration_path %>
            </p>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/feeds/unvote.js.erb
$("#feed<%= @feed.id%>").remove();
$("#container_feeds").prepend('<%= j render @feed  %>');
$(".col-md-6 blog-main box").remove();

app/views/feeds/update.js.erb
$("#feed<%= @feed.id%>").remove();
$("#myupdatefeed_<%= @feed.id %>").modal('hide');
$(".modal-backdrop").remove();
$("#container_feeds").prepend('<%= j render @feed %>');

app/views/feeds/upvote.js.erb
$("#feed<%= @feed.id%>").remove();
$()
$("#container_feeds").prepend('<%= j render @feed  %>');
$(".col-md-6 blog-main box").remove();

app/views/users/show.html.erb
<div class="col-md-4">
  <div>
    <%= link_to :back do  %>
        <i class="fa fa-long-arrow-left fa-2x"></i>
    <% end %>
  </div>
  <br>
  <div class="alert boxbackgroundcolor" role="alert">
    <%= image_tag(@user.avatar, :class=> "img-circle", size: "200") %>
      <% if @user.admin == true %>
          <h6>Admin</h6>
      <% else %>
          <h6>Normal User</h6>
      <% end %>
      <h2>
      <%= @user.first_name %>
      <%= @user.last_name %>
    </h2>
    <% if current_user && current_user != @user %>
        <%= link_to "Send Message", conversations_path(:sender_id => current_user.id , :recipient_id => @user.id ), :method => :post, class: "btn btn-success btn-xs start-conversation" %>
    <% elsif !current_user %>
        <%= link_to "Send Message", new_user_session_path %>
    <% end %>
    <h6><%= "Member Since "+(@user.created_at.to_formatted_s(:long_ordinal))%></h6>
    <% unless @user.about_me.nil? %>
        <p>
                <%= simple_format(@user.about_me) %>
        </p>
    <% end %>
    </div>

</div>
<div class="col-md-4" id="container_feeds">
	<h3>Feeds By <%= @user.username.capitalize %></h3>
  <% if @user.feeds.any? %>
      <% @user.feeds.reverse.each do |f| %>
            <div class="bs-component">
              <div class="alert alert-dismissible boxbackgroundcolor" id="feed<%= f.id%>">
                <button class="close" data-dismiss="alert" type="button">×</button>
                <i class="fa fa-quote-left fa-fw"></i><%= link_to f.text, f %><i class="fa fa-quote-right fa-fw"></i>
                <h6><%= time_ago_in_words(f.updated_at)+" ago."%> </h6>
                <hr class="margin5">
                <%= render partial: "feeds/votes", locals: {feed: f} %>
                <% if user_signed_in? %>
                    <% if can? :update, f %>
                        <button type="button" class="btn btn-xs" data-toggle="modal" data-target="#myupdatefeed_<%=f.id%>"><i class="fa fa-pencil-square-o">Edit</i></button>
                    <% end %>
                    <% if can? :destroy, f %>
                        <%= link_to f, method: :delete, remote: true, data: {confirm: "Are you sure?"} do %>
                            <i class="fa fa-lg fa-trash-o"></i>
                        <% end %>
                    <% end %>
                <% end %>
              </div>
            </div>
      <% end %>
  <%else %>
    <p>None</p>
  <% end %>

</div>
<div class="col-md-4">
	<h3>Comments By <%= @user.username.capitalize %></h3>
	<% if @user.comments.any? %>
      <% @user.comments.reverse.each do |c| %>
            <div class="bs-component">
              <div class="alert alert-dismissible boxbackgroundcolor" id="comment<%= c.id%>">
                <button class="close" data-dismiss="alert" type="button">×</button>
                <h4>"<%=link_to c.body, Feed.find(c.feed_id) %>"</h4>
                  <i class="fa fa-angle-double-right"> <%= link_to Feed.find(c.feed_id).user.username.capitalize, users_show_path(Feed.find(c.feed_id).user_id) %> :
                    "<%= link_to Feed.find(c.feed_id).text, Feed.find(c.feed_id)%>"</i>
                  <h6><%= time_ago_in_words(c.updated_at)+" ago."%> </h6>
              </div>
            </div>
      <% end %>
    <% else %>
        <p>None</p>
    <% end %>

</div>

app/views/users/unvote.js.erb
$("#feed<%= @feed.id%>").remove();
$("#container_feeds").prepend('<%= j render @feed  %>');

app/views/users/update.js.erb
$("#feed<%= @feed.id%>").remove();
$("#myupdatefeed_<%= @feed.id %>").modal('hide');
$(".modal-backdrop").remove();
$("#container_feeds").prepend('<%= j render @feed %>');

app/views/users/upvote.js.erb
$("#feed<%= @feed.id%>").remove();
$()
$("#container_feeds").prepend('<%= j render @feed  %>');