config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  get 'donate/index'

  get 'subscriptions/index'

  get 'subscriptions/plans'

  get 'subscriptions/stripe_checkout'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  match 'users/show/:id', to: 'users#show', via: 'get', as: 'users_show'
  match '/stripe_checkout' => 'subscriptions#stripe_checkout' , via: 'post'
  match '/pay_with_paypal' => 'subscriptions#pay_with_paypal' , via: 'post'
  resources :feeds do
    resources :comments
  end
  resources :feeds do
    member do
      put "like" => "feeds#upvote"
      put "unlike" => "feeds#downvote"
      put "unvote" => "feeds#unvote"
    end
  end

  resources :conversations do
    resources :messages, only: [:create]
  end

  resources :notifications

  post 'pusher/auth'
  root 'feeds#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    can :access, :rails_admin   # grant access to rails_admin
    can :dashboard              # grant access to the dashboard
    can :create , Feed
    can :update , Feed do |feed|
        feed.user.try(:username) == user.username
    end
    can :destroy, Feed do |feed|
        feed.user.try(:username) == user.username
    end
    can :destroy, Comment do |c|
        c.user.try(:username) == user.username
    end
    can :upvote, Feed
    can :downvote, Feed
    can :unvote, Feed
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :feed
  belongs_to :user
  validates :body, presence: true,length: { within: 1..200 }
  
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  end

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/models/feed.rb
class Feed < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	
  validates :text, presence: true,length: { within: 1..200 }
  belongs_to :user
  acts_as_votable

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :feed
  belongs_to :comment
  belongs_to :conversation


  def set_read
    self.read = true
  end

  def self.set_conversation_notification(recipient_id, sender_id, conversation)
    new_notification = Notification.create(read: false , user_id: recipient_id, sender_id: sender_id,conversation_id: conversation)
    new_notification.save
  end

  def self.get_count(user_id)
    User.find(user_id).notifications.where(read: false).count
  end

  def sender
    User.find(self.sender_id)
  end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validates :first_name, presence: true,
                    length: { minimum: 2 }
  validates :username, presence: true,
                    length: { minimum: 2 }, uniqueness: { case_sensitive: false }
  # validates :avatar, presence: true
  validates :time_zone, presence: true

  has_many :feeds, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  acts_as_voter

  def clear_conversation_notifications(conversation_id)
    self.notifications.where(conversation_id: conversation_id).each do |n|
      n.update_attributes(read: true)
    end
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
	# http_basic_authenticate_with name: "root", password: "passpass", except: [:index, :show]
	# before_action :authenticate_user! , except: [:index, :show]
	load_and_authorize_resource except: [:create, :index]

	def new
		@feed = current_user.feeds.build
	end

	def index
		@feeds = Feed.all
		@feed = Feed.new
		respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
		end
	end

	def create
		@feed = current_user.feeds.build(feed_params)
		@feed.name = current_user.username
		respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.js
      else
        format.html { render action: "index" }
        format.js
      end
    end
	end

	def edit
		@feed = Feed.find(params[:id])
	end

	def update
		@feed = Feed.find(params[:id])
		respond_to do |format|
			if @feed.update(feed_params)
	      format.html { redirect_to feeds_path }
	      format.js
			else
				format.html { render :edit }
	      format.js
			end
		end
	end

	def show
		@feed = Feed.find(params[:id])
	end

	def destroy
		@feed = Feed.find(params[:id])
		@feed.destroy
		respond_to do |format|
      format.html { redirect_to feeds_url,notice: 'Feed was successfully deleted.' }
      format.js
    end
	end

	def upvote
		@feed = Feed.find(params[:id])
		@feed.upvote_by current_user
		respond_to do |format|
			if @feed.upvote_by current_user
				format.html { redirect_to :back }
				format.js
			end
		end
	end

	def unvote
		@feed = Feed.find(params[:id])
		@feed.unvote_by current_user
		respond_to do |format|
			if @feed.unvote_by current_user
				format.html { redirect_to :back }
				format.js
			end
		end
	end

	def downvote
		@feed = Feed.find(params[:id])
		@feed.downvote_by current_user
		respond_to do |format|
			if @feed.downvote_by current_user
				format.html { redirect_to :back }
				format.js
			end
		end
	end

	
	private
	def feed_params
		params.require(:feed).permit(:name,:text)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def pusher_include_tag(version)
    domain = if request.ssl?
               'https://d3dy5gmtp8yhk7.cloudfront.net'
             else
               'http://js.pusher.com'
             end

    javascript_include_tag "#{domain}/#{version}/pusher.min.js"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
	
end

app/helpers/messages_helper.rb
module MessagesHelper
  def self_or_other(message)
    message.user == current_user ? "self" : "other"
  end

  def message_interlocutor(message)
    message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipient
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def conversation_interlocutor(conversation)
    conversation.recipient == current_user ? conversation.sender : conversation.recipient
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <hr class="margin5">
    A Sample Blog Built On Rails
    by <%= link_to "Nirajan Raj Pokharel", users_show_path(1) %>
    <div class="pull-right">
      <%= link_to "Donate !", donate_index_path %>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=current_user && Notification.get_count(current_user.id) > 0 ? "#{Notification.get_count(current_user.id)} New Notification !"  : "Feed It ! " %></title>
  <%= stylesheet_link_tag    'application', :media => 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://js.pusher.com/3.0/pusher.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/"><i class="fa fa-bolt fa-lg">
            Feed It</i> </a>
	    </div>
	    <div class="collapse navbar-collapse" id="myNavbar">
	      <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li><%# image_tag(current_user.avatar.url, :class=> "img-circle", :size => "50") %></li>
                <li><%= link_to current_user.first_name+" "+current_user.last_name, edit_user_registration_path, :title => "Edit Profile" %></li>
                <% if current_user.admin == true %>
                    <li><%= link_to "Manage Blog", rails_admin.dashboard_path %></li>
                <% end %>
                <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete%></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="badge"><%= Notification.get_count(current_user.id)%></span> New Notifications <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <% if current_user.notifications %>
                        <% current_user.notifications.reverse[0...5].each do |n| %>
                            <li><%= link_to "#{n.sender.username} sent you a new message" , n.conversation %></li>
                        <% end %>
                    <% end %>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "Show All", notifications_index_path %></li>
                  </ul>
                </li>
          <% else %>
                <li><%= link_to "Sign up", new_user_registration_path%></li>
                <li><%= link_to "Sign In", new_user_session_path%></li>

            <% end %>
            <li><%= link_to "Donate !", donate_index_path %></li>
          </ul>
	    </div>
	  </div>
	</nav>
	



	<div class="container">
      <br>
      <br>
      <br>
      <br>
		<% if notice %>
          <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= notice %>
          </div>
		<% end %>
		<% if alert %>
          <div class="alert alert-warning alert-dismissible alert-bottom" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= alert %>
          </div>
		<% end %>
	
		<%= yield %>
		
	</div>
	<div class="container">	
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>

</body>
</html>